# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['launch.py'],  
    pathex=[],
    binaries=[],
    datas=[
        ('verse_inserter/*.py', 'verse_inserter'),
        ('verse_inserter/config/*.py', 'verse_inserter/config'),
        ('verse_inserter/ui/*.py', 'verse_inserter/ui'), 
        ('verse_inserter/utils/*.py', 'verse_inserter/utils'),
    ],
    hiddenimports=[
        'verse_inserter.config.settings',  
        'verse_inserter.ui.main_window',
        'verse_inserter.utils.logger', 
        'verse_inserter.version',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'ttkbootstrap',
        'ttkbootstrap.themes',
        'docx',
        'docx.shared',
        'docx.enum.text',
        'aiohttp',
        'cryptography',
        'diskcache',
        'pydantic',
        'pydantic_settings',
        'tenacity',
        'colorlog',
        'PIL',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='VerseInserter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)